# Generated by Django 5.1.6 on 2025-02-26 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="chaimenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
                ("timedate", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ML", "masala chai"),
                            ("SL", "spiced lemon chai"),
                            ("TL", "tender lemon chai"),
                            ("NC", "normal chai"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
