# Generated by Django 5.1.6 on 2025-04-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaimenu",
            name="description",
            field=models.TextField(default=""),
        ),
    ]
