# Generated by Django 5.1.6 on 2025-04-09 17:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn", "0003_chaireviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="chaiCertificate",
            fields=[
                (
                    "chai",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="chaiCertificate",
                        serialize=False,
                        to="learn.chaimenu",
                    ),
                ),
                ("certificate_number", models.CharField(max_length=100)),
                ("issue_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                (
                    "chai_menu",
                    models.ManyToManyField(related_name="stores", to="learn.chaimenu"),
                ),
            ],
        ),
    ]
